excluded:
    - Pods

disabled_rules:
    - void_return
    - function_body_length
    - type_body_length
    - line_length
    - file_length
    - force_cast
    - trailing_whitespace
    - large_tuple
    - comment_spacing
    - multiple_closures_with_trailing_closure
    - switch_case_alignment

identifier_name:
    excluded: ["id", "vc", "i", "j", "x"]
    allowed_symbols: [“_”]
    validates_start_with_lowercase: warning

function_parameter_count:
    warning: 8
    error: 10

type_name:
    max_length:
    - 60 # warning
    - 1000


#type_body_length:
#  - 300 # warning
#  - 400 # error
